version: '0.0.1-alpha-{build}'
image: Visual Studio 2017 Preview
configuration:
 - Release
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
before_build:
  dotnet restore --verbosity m
build_script:
  - ps: dotnet build -c $Env:CONFIGURATION /p:PackageVersion=0.0.1-alpha-$env:APPVEYOR_BUILD_NUMBER
after_build:
  - ps: dotnet pack -c $Env:CONFIGURATION -o $env:APPVEYOR_BUILD_FOLDER\artifacts /p:PackageVersion=0.0.1-alpha-$env:APPVEYOR_BUILD_NUMBER
test_script:
  - ps: dotnet test test\Neuromatic.Tests\Neuromatic.Tests.csproj -c $Env:CONFIGURATION
artifacts:
  - path: artifacts\**\*.nupkg
cache:
- '%USERPROFILE%\.nuget\packages'