version: '0.0.1-alpha-{build}'
image: Visual Studio 2017
configuration:
 - Release
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
before_build:
  dotnet restore --verbosity m
build_script:
  - ps: dotnet build -c $Env:CONFIGURATION /p:PackageVersion=$env:APPVEYOR_BUILD_NUMBER
after_build:
  - ps: dotnet pack -c $Env:CONFIGURATION -o artifacts /p:PackageVersion=$env:APPVEYOR_BUILD_NUMBER
test_script:
  - ps: dotnet test -c $Env:CONFIGURATION
artifacts:
  - path: artifacts\**\*.nupkg
cache:
- '%USERPROFILE%\.nuget\packages'