&1189987678 version: 0.0.1.alpha-{build}
pull_requests:
  do_not_increment_build_number: &389385439 true
branches:
  only:
  - master
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: &2032546570 '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- &1455361020 ps: dotnet restore --verbosity m
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
before_package:
- ps: dotnet pack -c Release
artifacts:
- path: '**\*.nupkg'
  name: Nuget
deploy:
- provider: NuGet
  api_key:
    secure: 0ZoIjwzh6NJXkWK4zytT5T4ZjdCfckE4eLpqMoDSOy5Mr8OxNY4PCA8Y9c/TgDbo
  artifact: '**/*.nupkg'