&1990543290 version: 0.0.1.alpha-{build}
pull_requests:
  do_not_increment_build_number: &1025230487 true
branches:
  only:
  - master
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: &1035863009 '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- ps: dotnet restore --verbosity m
build:
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: 0ZoIjwzh6NJXkWK4zytT5T4ZjdCfckE4eLpqMoDSOy5Mr8OxNY4PCA8Y9c/TgDbo